name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8 am IST
    - cron : 00 14 * * * # 730 pm IST
    - cron : 00 06 * * 1-5 # 1130 am IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.3.1

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install Newman and Htmlextra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Collection with Newman
        run: | 
             newman run 'Inwarranty flow collection Copy.postman_collection.json' \
             -e QA.postman_environment.json \
             -r cli,htmlextra

      - name: Newman Report
        if: always() #ensure that the archive executed irrespective of whether the previous step has failed or not
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: Newman Report
          path: newman/*.html
      

          
